### ISSUE TITLE
Using mix version with WordPress

### ISSUE THREAD

**Issue by hectorsevillasandoval** [elambro/extract-css-media-queries#1]
Hi, I was trying to use this plugin on Laravel mix, but It seems is not working. Am I missing something in the configuration?

This is my set up:

`mix.sass('assets/scss/theme.scss', 'assets/dist/css/', {})
    .extractMediaQueries({
        breakpoints: [{
            minWidth: 992,
            verbose : false, 
            minify  : mix.inProduction(),
            combined: false,
            filename: `assets/dist/css/large.css`,
        }]
    });`

The generated CSS only has some bootstrap classes. 

![image](https://user-images.githubusercontent.com/1959346/99277413-67fb7100-27f3-11eb-8ff0-19568650f030.png)

**Comment by elambro** [comment]
@barcadictni Do you have media queries `@media (min-width: ...)` in your css? Can you show me `assets/scss/theme.scss`?

**Comment by hectorsevillasandoval** [comment]
Hi @elambro,

Here are the media queries:

![image](https://user-images.githubusercontent.com/1959346/99815088-7c02e380-2b0f-11eb-84c1-d3ee0af74cc5.png)

Should I change them?

**Comment by elambro** [comment]
The extension runs after the CSS is compiled, so it depends on when/how you’re using the scss vars. Can you share a part of the compiled CSS (in ‘dist’) where there is a media query that wasn’t extracted?

**Comment by hectorsevillasandoval** [comment]
Hi @elambro, here is the URL: [https://butlerfirm.cwdevelop.com/wp-content/themes/cws-theme-work-mix/assets/dist/css/theme.css](url)

**Comment by elambro** [comment]
Sorry for not getting back to you earlier, but I was looking for an example of a single media query that didn't work rather than an entire minified CSS file. It looks like it did separate out everything that was **min**-width: 992px and above. This plugin targets mobile first designs, so it doesn't extract those `max-width` media queries which target smaller screens. What was your expected output?
